platform :ios, '13.0'
pod 'YandexMobileAds', '8.3.0'
pod 'GoogleYandexMobileAdsAdapters'
pod 'UnityAdsYandexMobileAdsAdapters'
pod 'AppLovinYandexMobileAdsAdapters'
pod 'IronSourceYandexMobileAdsAdapters'
pod 'MintegralYandexMobileAdsAdapters'
pod 'MyTargetYandexMobileAdsAdapters'
pod 'VungleYandexMobileAdsAdapters'
pod 'BigoADSYandexMobileAdsAdapters'
pod 'YandexMobileAdsMediationExtras'


